config/routes.rb
Rails.application.routes.draw do
  resources :visits
  resources :providers
  resources :people

  get '/about', to: 'welcome#about', as: :about
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  has_one_attached :photo

  validates_presence_of :nickname
  validates_uniqueness_of :nickname

  def to_s
    nickname
  end

  def full_name
    [ first_name, middle_name, last_name ].compact.join(' ')
  end
end

app/models/provider.rb
class Provider < ApplicationRecord
  validates_presence_of :name, :primary_contact
  validates_uniqueness_of :primary_contact, scope: :name
  validates_uniqueness_of :name, scope: :primary_contact

  def to_s
    "#{primary_contact} at #{name}"
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :person, touch: true
  belongs_to :provider, touch: true
  has_many_attached :charts

  validates_presence_of :visited_at

  default_scope { order(visited_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "#{@person.nickname}'s record was saved." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "#{@person.nickname}'s record was updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "#{@person.nickname}'s record was deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :middle_name, :last_name, :nickname, :birthdate, :insurance_id, :notes, :photo)
    end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: "#{@provider.primary_contact}'s record was saved." }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: "#{@provider.primary_contact}'s record was updated." }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: "#{@provider.primary_contact}'s record was deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :address, :phone, :primary_contact, :notes)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was saved.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:visited_at, :person_id, :provider_id, :notes, charts: [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PEOPLE_TILE_LIMIT = 5
  PROVIDERS_TILE_LIMIT = 3
  VISITS_TILE_LIMIT = 7

  def index
    @people = Person.order(updated_at: :desc).limit(PEOPLE_TILE_LIMIT)
    @more_people = (Person.count > PEOPLE_TILE_LIMIT)

    @providers = Provider.order(updated_at: :desc).limit(PROVIDERS_TILE_LIMIT)
    @more_providers = (Provider.count > PROVIDERS_TILE_LIMIT)

    @visits = Visit.limit(VISITS_TILE_LIMIT)
    @more_visits = (Visit.count > VISITS_TILE_LIMIT)
  end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navigation_links
    {
      'Home'      => root_path,
      'People'    => people_path,
      'Providers' => providers_path,
      'Visits'    => visits_path
    }
  end

  def flash_class
    {
      'notice'  => 'alert-info',
      'success' => 'alert-success',
      'error'   => 'alert-danger',
      'alert'   => 'alert-warning'
    }
  end

  def flash_icon
    {
      'notice'  => 'info-circle',
      'success' => 'check-circle',
      'error'   => 'exclamation-circle',
      'alert'   => 'exclamation-triangle'
    }
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_alert.html.haml
.alert{ class: flash_class[flash_key] }
  %button.close{ type: 'button', data: { dismiss: 'alert'} }
    = icon('fas', 'times')
  = icon('fas', flash_icon[flash_key] + ' fa-2x fa-pull-left align-middle flash-icon', alt: flash_key)
  = flash_message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no")
    %title= content_for?(:title) ? yield(:title) : 'Chart Heap'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = favicon_link_tag '/favicon.ico', rel: 'shortcut icon'
    = javascript_include_tag 'application'
  %body
    %nav#header.navbar.navbar-expand-lg.navbar-light.bg-light.sticky-top
      = link_to root_path, class: 'navbar-brand' do
        %span.fa-stack.fa-1x{title: 'Chart Heap'}
          = icon('fas', 'trash-alt fa-stack-1x')
          = icon('fas', 'ban fa-stack-2x', style: 'color:Tomato')
        Chart Heap
      %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#main-menu'}  }
        = icon('fas', 'bars', title: 'Menu')
      .collapse.navbar-collapse#main-menu
        %ul.navbar-nav.mr-auto
          - navigation_links.each do |nav_item_text, nav_item_path|
            = active_link_to nav_item_text, nav_item_path,  class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
    - flash.each do |key, message|
      = render 'alert', flash_key: key, flash_message: message
    .container#content
      = yield
    %nav#footer.navbar.navbar-expand.fixed-bottom.navbar-dark.bg-dark.justify-content-center.small
      .navbar-text
        Chart Heap:
      %ul.navbar-nav
        = link_to 'About', about_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :middle_name
    = f.text_field :middle_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :birthdate
    = f.date_select :birthdate, start_year: Date.today.year - 120, end_year: Date.today.year
  .field
    = f.label :photo
    = f.file_field :photo
  .field
    = f.label :insurance_id
    = f.text_field :insurance_id
  .field
    = f.label :notes
    = f.text_area :notes
  .actions
    = f.submit 'Save'

app/views/people/_tile.html.haml
.person-tile{id: "person-#{person.id}"}
  = link_to person do
    .img-thumbnail.text-center
      - if person.photo.attached?
        = image_tag(person.photo.representation(resize: 'x100'), class: 'rounded')
      - else
        = icon('fas', 'user', class: 'img-fluid', style: 'font-size: 100px;')
      .caption
        %h4{ title: person.full_name }= person.nickname

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%section.container#people
  .row
    - @people.each do |person|
      .col-md-2
        = render 'people/tile', person: person
    .col-md-2.action-tile
      = link_to new_person_path, class: 'btn btn-primary' do
        = icon('fas', 'plus')
        %h3 Add...

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p
  %b First name:
  = @person.first_name
%p
  %b Middle name:
  = @person.middle_name
%p
  %b Last name:
  = @person.last_name
%p
  %b Nickname:
  = @person.nickname
%p
  %b Birthdate:
  = @person.birthdate
- if @person.photo.attached?
  %p
    = image_tag(@person.photo.representation(resize: '200x200'))
%p
  %b Insurance:
  = @person.insurance_id
%p
  %b Notes:
  = @person.notes

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Delete', @person, method: :delete, data: { confirm: 'Are you sure?' }
\|
= link_to 'Back', people_path

app/views/providers/_form.html.haml
= form_for @provider do |f|
  - if @provider.errors.any?
    #error_explanation
      %h2= "#{pluralize(@provider.errors.count, "error")} prohibited this provider from being saved:"
      %ul
        - @provider.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_area :address
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :primary_contact
    = f.text_field :primary_contact
  .field
    = f.label :notes
    = f.text_area :notes
  .actions
    = f.submit 'Save'

app/views/providers/_tile.html.haml
.provider-tile{id: "provider-#{provider.id}"}
  = link_to provider do
    .img-thumbnail.text-center
      = icon('fas', 'user-md', class: 'img-fluid', style: 'font-size: 100px;')
      .caption
        %h4{title: provider.primary_contact }= provider.primary_contact
        %p
          at
          = provider.name

app/views/providers/edit.html.haml
%h1 Editing provider

= render 'form'

= link_to 'Show', @provider
\|
= link_to 'Back', providers_path

app/views/providers/index.html.haml
%h1 Listing providers

%table
  %thead
    %tr
      %th Name
      %th Address
      %th Phone
      %th Primary contact
      %th Notes
      %th
      %th
      %th

  %tbody
    - @providers.each do |provider|
      %tr
        %td= provider.name
        %td= provider.address
        %td= provider.phone
        %td= provider.primary_contact
        %td= provider.notes
        %td= link_to 'Show', provider
        %td= link_to 'Edit', edit_provider_path(provider)
        %td= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Provider', new_provider_path

app/views/providers/new.html.haml
%h1 New provider

= render 'form'

= link_to 'Back', providers_path

app/views/providers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @provider.name
%p
  %b Address:
  = @provider.address
%p
  %b Phone:
  = @provider.phone
%p
  %b Primary contact:
  = @provider.primary_contact
%p
  %b Notes:
  = @provider.notes

= link_to 'Edit', edit_provider_path(@provider)
\|
= link_to 'Delete', @provider, method: :delete, data: { confirm: 'Are you sure?' }
\|
= link_to 'Back', providers_path

app/views/visits/_form.html.haml
= form_for @visit do |f|
  - if @visit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@visit.errors.count, "error")} prohibited this visit from being saved:"
      %ul
        - @visit.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :visited_at
    = f.datetime_select :visited_at
  .field
    = f.label :person
    = f.select :person_id, Person.all.map { |person| [person, person.id] }
  .field
    = f.label :provider
    = f.select :provider_id, Provider.all.map { |provider| [provider, provider.id] }
  .field
    = f.label :notes
    = f.text_field :notes
  .field
    = f.label :charts
    = f.file_field :charts, multiple: true
  .actions
    = f.submit 'Save'

app/views/visits/_tile.html.haml
.visit-tile{id: "visit-#{visit.id}"}
  = link_to visit do
    .img-thumbnail.text-center
      = icon('fas', 'notes-medical', class: 'img-fluid', style: 'font-size: 100px;')
      .caption
        %p
          %b= visit.person
          - if visit.visited_at.localtime.future?
            sees
          - else
            saw
          %br
          %b= visit.provider.primary_contact
          %br
          on
          %b= visit.visited_at.localtime.strftime('%Y %B %d - %H:%M')

app/views/visits/edit.html.haml
%h1 Editing visit

= render 'form'

= link_to 'Show', @visit
\|
= link_to 'Back', visits_path

app/views/visits/index.html.haml
%h1 Listing visits

%table
  %thead
    %tr
      %th Visited at
      %th Person
      %th Provider
      %th Notes
      %th
      %th
      %th

  %tbody
    - @visits.each do |visit|
      %tr
        %td= visit.visited_at.localtime.strftime('%Y %B %d - %H:%M')
        %td= visit.person.nickname
        %td= visit.provider.primary_contact
        %td= visit.notes
        %td= link_to 'Show', visit
        %td= link_to 'Edit', edit_visit_path(visit)
        %td= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Visit', new_visit_path

app/views/visits/new.html.haml
%h1 New visit

= render 'form'

= link_to 'Back', visits_path

app/views/visits/show.html.haml
%p#notice= notice

%p
  %b Visited at:
  = @visit.visited_at.localtime.strftime('%Y %B %d - %H:%M')
%p
  %b Person:
  = @visit.person.nickname
%p
  %b Provider:
  = @visit.provider.primary_contact
%p
  %b Notes:
  = @visit.notes
%p
  %b Chart:
  %ol
    - @visit.charts.each do |chart|
      %li= link_to image_tag(chart.representation(resize: '200x200')), rails_blob_path(chart, disposition: 'attachment')

= link_to 'Edit', edit_visit_path(@visit)
\|
= link_to 'Delete', @visit, method: :delete, data: { confirm: 'Are you sure?' }
\|
= link_to 'Back', visits_path

app/views/welcome/about.html.haml
%section#about
  .row
    .col-12
      :markdown
        # Chart Heap.
        ##### Trying to make sense of medical paperwork before you roundfile it.

        ---

        ### About

        Chart Heap is a
        [free/libre open source application](https://en.wikipedia.org/wiki/Free_and_open-source_software)
        written to scratch an itch.

        It is licensed under the
        [GPL v3 license](https://www.gnu.org/licenses/gpl-3.0.en.html).

        The original source is available at
        [gitlab.com/bear454/chartheap](https://gitlab.com/bear454/chartheap). Pull requests
        are welcome!

        ---

        ### Attribution

        The background is based on
        ['Shredded'](https://commons.wikimedia.org/wiki/File:Shredded.jpg)
        from
        [Mike Haw](https://flickr.com/people/44124456291@N01),
        discovered on
        [Wikimedia Commons](https://commons.wikimedia.org/)

        The application builds on, and is grateful to the developers of the following framework components:

        * [Ruby](https://www.ruby-lang.org/en/)
        * [Rails](https://rubyonrails.org/)
        * [jQuery](https://jquery.com/)
        * [Bootstrap](https://getbootstrap.com/)
        * [FontAwesome Free](https://fontawesome.com/free)
        * [Various ruby gems](https://gitlab.com/bear454/chartheap/blob/master/Gemfile.lock)

        ----

        ### Copyright

        Unless noted otherwise, the source code for Chart Heap is &copy; 2019
        [James Mason 'bear454'](https://bear454.com).

app/views/welcome/index.html.haml
%section#people
  .navbar
    = link_to icon('fas', 'users', 'People'), people_path, class: 'navbar-brand'
    = link_to icon('fas', 'plus', 'Add a new person'), new_person_path, class: 'btn btn-secondary'
  .row
    - @people.each do |person|
      .col-md-2
        = render 'people/tile', person: person
    - if @more_people
      .col-md-2.action-tile
        = link_to people_path do
          = icon('fas', 'angle-double-right')
          %h3 More...

%section#providers
  .navbar
    = link_to icon('fas', 'user-md', 'Providers'), providers_path, class: 'navbar-brand'
    = link_to icon('fas', 'plus', 'Add a new provider'), new_provider_path, class: 'btn btn-secondary'
  .row
    - @providers.each do |provider|
      .col-md-3
        = render 'providers/tile', provider: provider
    - if @more_providers
      .col-md-2.action-tile
        = link_to providers_path do
          = icon('fas', 'angle-double-right')
          %h3 More...

%section#visits
  .navbar
    = link_to icon('fas', 'notes-medical', 'Recent visits'), visits_path, class: 'navbar-brand'
    = link_to icon('fas', 'plus', 'Add a new visit'), new_visit_path, class: 'btn btn-secondary'
  .row
    - @visits.each do |visit|
      .col-md-3
        = render 'visits/tile', visit: visit
    - if @more_visits
      .col-md-2.action-tile
        = link_to visits_path do
          = icon('fas', 'angle-double-right')
          %h3 More...